name: guacamole
services:
  guacd:
    image: guacamole/guacd
    build: https://github.com/apache/guacamole-server.git
    restart: unless-stopped
    expose:
      - 4822
    networks:
      - guacamole-network

  guacamole:
    image: guacamole/guacamole
    build: 
      context: .
      target: client
      dockerfile: Dockerfile
      args:
        - WEBAPP_CONTEXT=ROOT
    environment:
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
    restart: unless-stopped
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - guacamole-network

networks:
  guacamole-network:
    driver: bridge