name: Build & Deploy

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Guacamole Server
        uses: actions/checkout@v4
        with:
          repository: apache/guacamole-server
          path: guacamole-server

      - name: Checkout Guacamole Client
        uses: actions/checkout@v4
        with:
          repository: apache/guacamole-client
          path: guacamole-client

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Docker meta for guacamole server
        id: server-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ secrets.DOCKER_REPOSITORY_USERNAME }}/${{ github.event.repository.name }}-server
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Deploy Server to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: LABEL=https://github.com/${{ secrets.DOCKER_REPOSITORY_USERNAME }}/${{ github.event.repository.name }}-server
          platforms: linux/arm64
          push: true
          tags: ${{ steps.server-meta.outputs.tags }}
          labels: ${{ steps.server-meta.outputs.labels }}

      - name: Docker meta for guacamole client
        id: client-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ secrets.DOCKER_REPOSITORY_USERNAME }}/${{ github.event.repository.name }}-client
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Deploy Server to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: LABEL=https://github.com/${{ secrets.DOCKER_REPOSITORY_USERNAME }}/${{ github.event.repository.name }}-client
          platforms: linux/arm64
          push: true
          tags: ${{ steps.client-meta.outputs.tags }}
          labels: ${{ steps.client-meta.outputs.labels }}

      - name: Logout from Docker Hub
        run: docker logout
