name: Build & Deploy

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_TOKEN }}

      - name: Docker meta for server
        id: meta-server
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ secrets.DOCKER_REPOSITORY_USERNAME }}/${{ github.event.repository.name }}-server
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Deploy Server to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          target: server
          build-args: LABEL=https://github.com/${{ secrets.DOCKER_REPOSITORY_USERNAME }}/${{ github.event.repository.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}

      - name: Docker meta for client
        id: meta-client
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ secrets.DOCKER_REPOSITORY_USERNAME }}/${{ github.event.repository.name }}-client
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Deploy client to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          target: client
          build-args: LABEL=https://github.com/${{ secrets.DOCKER_REPOSITORY_USERNAME }}/${{ github.event.repository.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-client.outputs.tags }}
          labels: ${{ steps.meta-client.outputs.labels }}

      - name: Logout from Docker Hub
        run: docker logout
